### ISSUE TITLE
Unknown state ID errors in CI

### ISSUE THREAD

**Issue by atomb** [GaloisInc/cryptol#1261]
Recently some CI runs, such as [this one](https://github.com/GaloisInc/cryptol/pull/1257/checks?check_run_id=3246876445#step:10:100), have failed with an `argo_client.interaction.ArgoException: Unknown state ID` error message. So far, I've only seen these on macOS, but it's possible that they could occur on other platforms, too.

In case the log above gets garbage collected, the relevant snippet of error message is as follows:
````
======================================================================
ERROR: test_CplxQ (test_CplxQNewtype.TestCplxQ)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/work/cryptol/cryptol/cryptol-remote-api/python/tests/cryptol/test_CplxQNewtype.py", line 13, in test_CplxQ
    forty_two = c.eval("fortyTwo").result()
  File "/Users/runner/Library/Caches/pypoetry/virtualenvs/cryptol-L3Aq5hhJ-py3.7/lib/python3.7/site-packages/argo_client/interaction.py", line 168, in result
    return self.process_result(self._result_and_state_and_out_err()[0])
  File "/Users/runner/Library/Caches/pypoetry/virtualenvs/cryptol-L3Aq5hhJ-py3.7/lib/python3.7/site-packages/argo_client/interaction.py", line 153, in _result_and_state_and_out_err
    raise self.process_error(exception)
argo_client.interaction.ArgoException: Unknown state ID b13110c6-f4b2-4363-a6c1-74d931eca90b

----------------------------------------------------------------------
````

**Comment by pnwamk** [comment]
Fixed in `cryptol` by https://github.com/GaloisInc/cryptol/pull/1273
