### ISSUE TITLE
[Remote API] Crash trying to `check` `property` in parameterized module

### ISSUE THREAD

**Issue by WeeknightMVP** [GaloisInc/cryptol#1623]
Trying to `:check` a `property` in a parameterized module correctly fails in the Cryptol REPL with an explanation, but trying an equivalent `CryptolConnection.check` in the Remote API for Python causes a panic.  (The Python interpreter remains open and can correctly check an instance of the property.)

```
.../cryptol/cryptol-remote-api/python$ poetry shell
(poetry) .../cryptol/cryptol-remote-api/python$ cd ../..
(poetry) .../cryptol$ export PATH=$(dirname $(cabal v2-exec which cryptol)):$PATH
(poetry) .../cryptol$ export CRYPTOL_SERVER=$(cabal v2-exec which cryptol-remote-api)
(poetry) .../cryptol$ cd ../cryptol-specs
(poetry) .../cryptol-specs$ export CRYPTOLPATH="$(pwd)/Primitive/Asymmetric/Cipher/ML-KEM:$(pwd)"
(poetry) .../cryptol-specs$ cryptol
...version 3.0.0.99 (3b9f6c5, modified)
Cryptol> :m specification
specification (Parameterized)> :check rounding

Expression depends on definitions from a parameterized module:
  specification::rounding
Cryptol> :quit
(poetry) .../cryptol-specs$ cd ../cryptol/cryptol-remote-api/python
(poetry) .../cryptol/cryptol-remote-api/python$ python
Python 3.11.7 (main, Dec  8 2023, 18:56:57) [GCC 9.4.0] on linux
>>> from os import environ
>>> from cryptol import connect
>>> environ['CRYPTOLPATH']
'.../cryptol-specs/Primitive/Asymmetric/Cipher/ML-KEM:.../cryptol-specs'
>>> c = connect(reset_server=True)
>>> c.load_module('specification').result()
[]
>>> c.check('rounding').result()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/.cache/pypoetry/virtualenvs/cryptol-WSsLqK6b-py3.11/lib/python3.11/site-packages/argo_client/interaction.py", line 178, in result
    return self.process_result(self._result_and_state_and_out_err()[0])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.cache/pypoetry/virtualenvs/cryptol-WSsLqK6b-py3.11/lib/python3.11/site-packages/argo_client/interaction.py", line 167, in _result_and_state_and_out_err
    raise self.process_error(exception)
argo_client.interaction.ArgoException: Internal error You have encountered a bug in Cryptol's implementation.
*** Please create an issue at https://github.com/GaloisInc/cryptol/issues

%< ---------------------------------------------------
  Revision:  3b9f6c5416e4ca523d337fba2d20c39dbe784309
  Branch:    master (uncommited files present)
  Location:  [Eval] evalExpr
  Message:   var `specification::rounding` (4813) is not defined
             [4128 <<prim>> 4129 -> <polymorphic value>
4130 -> <polymorphic value> 4131 <<prim>> 4132 <<prim>>
4133 <<prim>> 4134 <<prim>> 4135 <<prim>> 4136 <<prim>>
4137 <<prim>> 4139 <<prim>> 4141 <<prim>> 4143 <<prim>>
4144 <<prim>> 4145 <<prim>> 4146 <<prim>> 4148 <<prim>>
4149 <<prim>> 4150 <<prim>> 4151 <<prim>> 4152 <<prim>>
4154 <<prim>> 4155 <<prim>> 4156 <<prim>> 4157 <<prim>>
4158 <<prim>> 4159 <<prim>> 4161 <<prim>> 4162 <<prim>>
4164 <<prim>> 4165 <<prim>> 4166 <<prim>> 4167 <<prim>>
4168 <<prim>> 4170 <<prim>> 4171 <<prim>>
4172 -> <polymorphic value> 4173 -> <polymorphic value>
4175 <<prim>> 4176 <<prim>> 4177 <<prim>> 4178 <<prim>>
4179 -> <polymorphic value> 4180 -> <polymorphic value>
4181 -> <polymorphic value> 4183 <<prim>>
4184 -> <polymorphic value> 4185 -> <polymorphic value>
4186 -> <polymorphic value> 4187 <<prim>> 4188 <<prim>>
4189 -> <function> 4190 -> <function> 4191 -> <function>
4192 <<prim>> 4193 <<prim>> 4194 -> <polymorphic value>
4195 -> <polymorphic value> 4196 -> <polymorphic value>
4197 -> <polymorphic value> 4198 -> <polymorphic value>
4199 <<prim>> 4200 <<prim>> 4201 <<prim>> 4202 <<prim>>
4203 <<prim>> 4204 <<prim>> 4205 -> <polymorphic value>
4206 <<prim>> 4207 <<prim>> 4208 <<prim>> 4209 <<prim>>
4210 <<prim>> 4211 <<prim>> 4212 -> <polymorphic value>
4213 -> <polymorphic value> 4214 -> <polymorphic value>
4215 -> <polymorphic value> 4216 <<prim>> 4217 <<prim>>
4218 <<prim>> 4219 <<prim>> 4220 <<prim>>
4221 -> <polymorphic value> 4222 <<prim>>
4223 -> <polymorphic value> 4224 <<prim>> 4225 <<prim>>
4226 -> <polymorphic value> 4227 -> <polymorphic value>
4228 -> <polymorphic value> 4229 -> <polymorphic value>
4230 -> <polymorphic value> 4231 <<prim>> 4232 <<prim>>
4233 <<prim>> 4234 <<prim>> 4235 <<prim>>
4236 -> <polymorphic value> 4237 <<prim>>
4238 -> <polymorphic value> 4239 -> <polymorphic value>
4240 <<prim>> 4241 <<prim>> 4242 -> <polymorphic value>
4243 -> <polymorphic value> 4244 -> <polymorphic value>
4245 -> <polymorphic value> 4246 -> <polymorphic value>
4247 -> <polymorphic value> 4248 <<prim>> 4249 <<prim>>
4250 -> <polymorphic value> 4251 -> <polymorphic value>
4252 -> <polymorphic value> 4253 -> <polymorphic value>
4254 <<prim>> 4255 -> <polymorphic value>
4256 -> <polymorphic value> 4257 -> <polymorphic value>
4258 -> <polymorphic value> 4259 -> <polymorphic value>
4260 -> <polymorphic value> 4261 -> <polymorphic value>
4262 -> <polymorphic value> 4669 -> <polymorphic value>
4670 -> <polymorphic value> 4671 -> <polymorphic value>
4672 -> <polymorphic value> 4673 -> <polymorphic value>
4674 -> <polymorphic value> 4675 -> <polymorphic value>
4676 -> <polymorphic value> 4677 -> <polymorphic value>
4678 -> <polymorphic value> 4679 -> <polymorphic value>
4680 -> <polymorphic value> 4681 -> [1, 32898,
 9223372036854808714, 9223372039002292224, 32907, 2147483649,
 9223372039002292353, 9223372036854808585, 138, 136, 2147516425,
 2147483658, 2147516555, 9223372036854775947, 9223372036854808713,
 9223372036854808579, 9223372036854808578, 9223372036854775936,
 32778, 9223372039002259466, 9223372039002292353,
 9223372036854808704, 2147483649, 9223372039002292232]
4682 -> <polymorphic value> 4683 -> <polymorphic value>
4684 -> <polymorphic value> 4685 -> <function> 4686 -> [True,
 False, False, False, False, ...] 4687 -> <function>
4688 -> <function> 4766 -> <polymorphic value>
4767 -> <polymorphic value> 4774 -> <polymorphic value>
4775 -> True 4776 -> True 4777 -> True 4778 -> True
4782 -> <polymorphic value> 4783 -> True 4784 -> True 4785 -> True
4786 -> True]
CallStack (from HasCallStack):
  panic, called at src/Cryptol/Utils/Panic.hs:21:9 in cryptol-3.0.0.99-inplace:Cryptol.Utils.Panic
  panic, called at src/Cryptol/Eval.hs:183:9 in cryptol-3.0.0.99-inplace:Cryptol.Eval
%< ---------------------------------------------------
>>> c.load_module('ml_kem1024').result()
[]
>>> c.check('rounding').result()
CheckReport(success=True, args=[], error_msg=None, tests_run=1, tests_possible=1)
```

**Comment by RyanGlScott** [comment]
I believe that the Cryptol REPL fails with a proper exception since we explicitly check for this in [`validEvalContext`](https://github.com/GaloisInc/cryptol/blob/7ab8ca5820e42609cc82dd4d9b351874efbf8b2a/src/Cryptol/REPL/Monad.hs#L583-L584). We don't currently call `validEvalContext` from the remote API, but there are some TODOs about it:

* https://github.com/GaloisInc/cryptol/blob/7ab8ca5820e42609cc82dd4d9b351874efbf8b2a/cryptol-remote-api/src/CryptolServer/Check.hs#L59
* https://github.com/GaloisInc/cryptol/blob/7ab8ca5820e42609cc82dd4d9b351874efbf8b2a/cryptol-remote-api/src/CryptolServer/Sat.hs#L58

It seems likely that fixing these TODOs would resolve the issue seen here.
